engines:
  csslint:
    enabled: true
  phpmd:
    enabled: true
    checks:
      UnusedPrivateMethod:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/LongVariable:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  checks:
      PSR1 Methods CamelCapsMethodName NotCamelCaps:
        enabled: false
