engines:
  phpmd:
    enabled: true
    checks:
      UnusedPrivateMethod:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/LongVariable:
        enabled: false
